lsi: false
safe: true
source: "https://github.com/Worthy-Alpaca/SpeasierJS"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-slate